# Sakura PvP Configuration

# Server Selector Configuration
selector:
  material: COMPASS
  name: "<dark_purple>Server Selector"
  slot: 4

gui:
  title: "<dark_purple>Sakura Network"
  size: 27
  use-background: true
  background-material: BLACK_STAINED_GLASS_PANE

servers:
  practice:
    display-name: "<dark_purple>Practice"
    material: DIAMOND_SWORD
    slot: 11
    server-id: "practice"  # BungeeCord server ID
    description:
      - "<white>Practice your PvP skills"
      - "<white>with custom kits and arenas"
      - ""
      - "<dark_purple>» Click to join!"

  ffa:
    display-name: "<dark_purple>FFA"
    material: NETHERITE_SWORD
    slot: 13
    server-id: "ffa"  # BungeeCord server ID
    description:
      - "<white>Jump into instant PvP action"
      - "<white>in various themed arenas"
      - ""
      - "<dark_purple>» Click to join!"

  duels:
    display-name: "<dark_purple>Duels"
    material: GOLDEN_SWORD
    slot: 15
    server-id: "duels"  # BungeeCord server ID
    description:
      - "<white>1v1 battles with custom"
      - "<white>kits and ranked matches"
      - ""
      - "<dark_purple>» Click to join!"