# Shadow Hub Configuration
# Server Selector Configuration
selector:
  material: COMPASS
  name: "<dark_purple>Server Selector"
  slot: 4
  custom-model-data: 1001
gui:
  title: "<dark_purple>Shadow Network"
  size: 27
  use-background: true
  background-material: BLACK_STAINED_GLASS_PANE
servers:
  duels:
    display-name: "<dark_purple>Duels"
    material: ORANGE_CONCRETE
    slot: 11
    server-id: "duels"  # BungeeCord server ID
    enabled: true  # Queue status persistence
    description:
      - "<white>1v1 battles with custom"
      - "<white>kits and ranked matches"
      - ""
      - "<gray>Queue Status: <green>Open"
      - ""
      - "<dark_purple>» Click to join queue!"
  pit:
    display-name: "<dark_purple>Pit"
    material: PINK_CONCRETE
    slot: 13
    server-id: "pit"  # BungeeCord server ID
    enabled: true  # Queue status persistence
    description:
      - "<white>Join the chaotic arena"
      - "<white>and fight for supremacy"
      - ""
      - "<gray>Queue Status: <green>Open"
      - ""
      - "<dark_purple>» Click to join queue!"
  ffa:
    display-name: "<dark_purple>FFA"
    material: CYAN_CONCRETE
    slot: 15
    server-id: "ffa"  # BungeeCord server ID
    enabled: true  # Queue status persistence
    description:
      - "<white>Jump into instant PvP action"
      - "<white>in various themed arenas"
      - ""
      - "<gray>Queue Status: <green>Open"
      - ""
      - "<dark_purple>» Click to join queue!"
# Queue Configuration
queue:
  process-interval: 20
  messages:
    joined: "<dark_purple>You joined the queue for %server%!"
    left: "<dark_purple>You left the queue!"
    disabled: "<dark_purple>This queue is currently disabled!"
    locked: "<dark_purple>This queue is currently locked!"
  action-bar:
    format: "<dark_purple>In Queue: %server% | Position: %position%/%total% | Time: %time%"

# Player Configuration
player:
  # Delay in ticks before teleporting to spawn (20 ticks = 1 second)
  # Increased to 40 ticks (2 seconds) to prevent "movement packet invalid" errors
  spawn-teleport-delay: 40
  # Welcome message shown to players when they join
  welcome-message:
    - ""
    - "<bold><gold>● WELCOME TO SHADOW NETWORK ●</gold></bold>"
    - "<bold><white>━━━━━━━━━━━━━━━━━━━━━━━</white></bold>"
    - "<white>The home of PvP</white>"
    - ""

# Launch Pad Configuration
launch-pads:
  enabled: true
  # Stone pressure plate (basic)
  stone:
    material: STONE_PRESSURE_PLATE
    multiplier: 2.0
    vertical-boost: 0.8
    cooldown: 1000
    particle: CLOUD
    sound: BLOCK_IRON_TRAPDOOR_OPEN
  # Heavy weighted pressure plate (medium)
  heavy:
    material: HEAVY_WEIGHTED_PRESSURE_PLATE
    multiplier: 3.0
    vertical-boost: 1.2
    cooldown: 1500
    particle: FIREWORK
    sound: ENTITY_FIREWORK_ROCKET_LAUNCH
  # Light weighted pressure plate (strong)
  light:
    material: LIGHT_WEIGHTED_PRESSURE_PLATE
    multiplier: 4.0
    vertical-boost: 1.5
    cooldown: 2000
    particle: TOTEM_OF_UNDYING
    sound: ENTITY_WITHER_SHOOT

# EnderButt Configuration
enderbutt:
  enabled: true
  name: "<#9AABBD>Ender Butt"
  lore:
    - "<gray>Throw to ride the ender pearl!"
    - "<gray>Wheeeeeee!"

# Autograph Book Configuration
autographbook:
  enabled: true
  name: "<gold>Autograph Book"
  lore:
    - "<gray>Collect autographs from other players!"
    - "<gray>Right-click to view your collection."
    - "<gray>Left-click a player to request their autograph."
  gui:
    title: "<gold>Autograph Collection"
    size: 54
    background-material: BLACK_STAINED_GLASS_PANE
    header-material: WRITABLE_BOOK
