name: Shadow
version: '1.0'
main: com.shadow.Shadow
api-version: '1.21'
authors: [ Banker ]
commands:
  setspawn:
    description: Set the spawn location
    usage: /setspawn

  spawn:
    description: Teleport to the spawn location
    usage: /spawn

  queue:
    description: Queue management command
    usage: |
      /queue join <server> - Join a server queue
      /queue leave - Leave current queue
      /queue control <disable|enable> <server> - Control queues
    aliases: [q]

  shadow:
    description: Admin commands for the Shadow plugin
    usage: |
      /shadow info - Show plugin information
      /shadow reload - Reload plugin configuration
    aliases: [sh]

permissions:
  shadow.setspawn:
    description: Allows setting the spawn location
    default: op

  shadow.queue.admin:
    description: Allows controlling server queues
    default: op

  shadow.admin:
    description: Allows access to Shadow plugin administration commands
    default: op
